highlighter: rouge
paginate: 20
paginate_path: "/page/page:num/"
markdown: kramdown
host: 0.0.0.0
gems: [jekyll-paginate]
home_url: "https://heeyeun.github.io"
representing_image: ""
future: true
title: Heeyeun.GitHub.io
description: 
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman